### ISSUE TITLE
 Too many records, Column=DMS_Content_ID

### ISSUE THREAD

**Issue by norbertbede** [logilite/logilite-DMS#10]
we need to change fieldtype to ID or search.

`MS_Content.DMS_Content_ID: Loader - Too many records, Column=DMS_Content_ID, Table=DMS_Version [183]`

**Comment by sbhimani12** [comment]
Change committed [Commit: c5e64c257407fe0635c1d4532fb2aa5c58097ae5 [c5e64c2] ]
