### ISSUE TITLE
Improved Migration from Attachment

### ISSUE THREAD

**Issue by norbertbede** [logilite/logilite-DMS#5]
we found some issues around migrate attachments to dms content. 
- rollback issues
- allow run multiple times the migration process.

**Comment by igorpojzl** [comment]
Patch adding commit after each successfull migration
[MigrateAttachmentToDMS_Commit.patch](https://github.com/logilite/logilite-DMS/files/13560095/MigrateAttachmentToDMS_Commit.patch)

**Comment by sbhimani12** [comment]
Patch changes committed [Commit: 824eba89b2fb91194e0befc74ffe573bc776cc0c [824eba8]]
